# Generated by Django 2.2.13 on 2020-06-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(unique=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('release_date', models.DateField(null=True)),
                ('language', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=100)),
                ('adult', models.BooleanField(default=False)),
                ('popularity', models.FloatField(null=True)),
            ],
        ),
    ]
