# Generated by Django 2.2.13 on 2020-06-22 08:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200621_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('mylist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[], null=True, size=None)),
            ],
        ),
    ]
