# Generated by Django 2.2.13 on 2020-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AlterField(
            model_name='movies',
            name='mid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
