# Generated by Django 2.2.13 on 2020-06-22 11:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200622_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='mylist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[0], null=True, size=None),
        ),
    ]
