# Generated by Django 2.2.13 on 2020-06-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200622_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='lid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
